/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import com.google.inject.Guice;
import com.google.inject.Injector;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

import interpolation.Grid;
import interpolation.GridInterpolator;
import interpolation.NearestNeighborsGridInterpolator;
import interpolation.Point;
import interpolation.Polygon;

/**
 *
 * @author alsm0813
 */
public class GeographyGUI extends javax.swing.JFrame {

    public static final String STOP = "Stop";
    public static final String START = "Start";
    private ExecutorService executorService = Executors.newSingleThreadExecutor();
    private Lock lock = new ReentrantLock();

    private final GridCSVHelper gridCSVHelper;

    private final GridRenderer gridRenderer;

    private final GridInterpolator gridInterpolator;

    public GeographyGUI() {
        Injector injector = Guice.createInjector(new GeographyModule());
        this.gridCSVHelper = injector.getInstance(GridCSVHelper.class);
        this.gridRenderer = injector.getInstance(GridRenderer.class);
        this.gridInterpolator = injector.getInstance(GridInterpolator.class);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        probeDataLabel = new javax.swing.JLabel();
        probeDataTextField = new javax.swing.JTextField();
        probeDataButton = new javax.swing.JButton();
        boundariesLabel = new javax.swing.JLabel();
        boundariesTextField = new javax.swing.JTextField();
        boundariesButton = new javax.swing.JButton();
        gridStepTextField = new javax.swing.JTextField();
        launchButton = new javax.swing.JButton();
        gridStepLabel = new javax.swing.JLabel();
        interpolationProgressBar = new javax.swing.JProgressBar();
        interpolationProgressBar.setPreferredSize(new Dimension(250,20));
        interpolationProgressBar.setMaximumSize(new Dimension(250,20));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        probeDataLabel.setText("Data");

        probeDataTextField.setEnabled(false);
        probeDataTextField.setPreferredSize(new Dimension(300,20));
        probeDataTextField.setMaximumSize(new Dimension(300,20));
        probeDataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probeDataTextFieldActionPerformed(evt);
            }
        });

        probeDataButton.setText("Browse");
        probeDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probeDataButtonActionPerformed(evt);
            }
        });

        boundariesLabel.setText("Boundaries");

        boundariesTextField.setEnabled(false);
        boundariesTextField.setPreferredSize(new Dimension(300,20));
        boundariesTextField.setMaximumSize(new Dimension(300,20));
        boundariesTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundariesTextFieldActionPerformed(evt);
            }
        });

        boundariesButton.setText("Browse");
        boundariesButton.setActionCommand("");
        boundariesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boundariesButtonActionPerformed(evt);
            }
        });

        gridStepTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        gridStepTextField.setText("1");
        gridStepTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gridStepTextFieldActionPerformed(evt);
            }
        });

        launchButton.setText(START);
        launchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchButtonActionPerformed(evt);
            }
        });

        gridStepLabel.setText("Grid Step");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(probeDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boundariesLabel))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gridStepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gridStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(interpolationProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE))
                    .addComponent(probeDataTextField)
                    .addComponent(boundariesTextField))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boundariesButton)
                    .addComponent(probeDataButton)
                    .addComponent(launchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(probeDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                        .addComponent(probeDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(probeDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(boundariesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(boundariesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boundariesTextField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(launchButton)
                    .addComponent(interpolationProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(gridStepTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gridStepLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        setResizable(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gridStepTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gridStepTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gridStepTextFieldActionPerformed

    private void probeDataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probeDataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_probeDataTextFieldActionPerformed

    private void probeDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probeDataButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV_Files", "csv");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setFileFilter(filter);
        int ret = fileChooser.showDialog(null, "Open");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            probeDataTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_probeDataButtonActionPerformed

    private void boundariesTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundariesTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boundariesTextFieldActionPerformed

    private void boundariesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boundariesButtonActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("CSV_Files", "csv");
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setFileFilter(filter);
        int ret = fileChooser.showDialog(null, "Open");
        if (ret == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            boundariesTextField.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_boundariesButtonActionPerformed

    private void launchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchButtonActionPerformed
        if (lock.tryLock()) {
            try {
                if (START.equals(launchButton.getText())) {
                    launchButton.setText(STOP);
                    executorService.submit((Runnable) () -> {
                        try {
                            Map<Point, Double> probeData = gridCSVHelper.read3DGrid(probeDataTextField.getText());
                            System.out.println(probeData);

                            List<Point> boundaries = gridCSVHelper.read2DGrid(boundariesTextField.getText());
                            System.out.println(boundaries);

                            Polygon polygon = new Polygon(boundaries);
                            int h = Integer.parseInt(gridStepTextField.getText());
                            Grid interpolatedGrid = gridInterpolator.interpolate(new Grid(probeData, polygon, h));
                            gridRenderer.render(interpolatedGrid);
                        } catch (NumberFormatException e) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Grid step must be integer",
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        } catch (InterruptedException e) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Grid interpolation has been interrupted",
                                    "Info",
                                    JOptionPane.INFORMATION_MESSAGE
                            );
                        } catch (IOException e) {
                            JOptionPane.showMessageDialog(
                                    this,
                                    "Error has occurred while trying to read csv file",
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        } catch (Exception e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(
                                    this,
                                    e.getMessage(),
                                    "Error",
                                    JOptionPane.ERROR_MESSAGE
                            );
                        } finally {
                            launchButton.setText(START);
                        }
                    });
                } else {
                    executorService.shutdownNow();
                    launchButton.setText(START);
                }
            } finally {
                lock.unlock();
            }
        }
    }//GEN-LAST:event_launchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GeographyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GeographyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GeographyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GeographyGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeographyGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boundariesButton;
    private javax.swing.JLabel boundariesLabel;
    private javax.swing.JTextField boundariesTextField;
    private javax.swing.JLabel gridStepLabel;
    private javax.swing.JTextField gridStepTextField;
    private javax.swing.JProgressBar interpolationProgressBar;
    private javax.swing.JButton launchButton;
    private javax.swing.JButton probeDataButton;
    private javax.swing.JLabel probeDataLabel;
    private javax.swing.JTextField probeDataTextField;
    // End of variables declaration//GEN-END:variables
}
